spring:
  application:
    name: book
  config:
    import: optional:application-secret.properties
  logging:
    level:
      org.springframework.orm.jpa: DEBUG
      org.springframework.transaction: DEBUG
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: never